# classes = {
#     "Warlock": {
#          "Demonology": {
#             "strength": 2.27,
#             "agility": 3.61,
#             "intellect": 0.38,
#         
#             "hit": 1.00,
#             "expertise": 3.28,
#             "attack power": 1.00,
#             "crit": 2.54,
#             "haste": 1.53,
#             "armor penetration": 0.47,
#             },
#         },
#     "Druid": {
#         "Feral": {
#             "strength": 2.27,
#             "agility": 3.61,
#             "intellect": 0.38,
#         
#             "hit": 1.00,
#             "expertise": 3.28,
#             "attack power": 1.00,
#             "crit": 2.54,
#             "haste": 1.53,
#             "armor penetration": 0.47,
#             },
#         "Balance": {
#             "intellect": 2.27,
#             "spirit": 3.61,
#             "spell damage": 0.38,
#             "arcane damage": 0.17,
#             "nature damage": 1.00,
#             "spell hit": 3.28,
#             "spell crit": 1.00,
#             "spell haste": 2.54,
#             "mp5": 1.53,
#             },
#         },
#     "Hunter": {
#         "Survival": {
#             "strength": 0.15,
#             "agility": 2.5,
#             "intellect": 0.01,
#         
#             "hit": 3.57,
#             "attack power": 1.00,
#             "crit": 1.78,
#             "haste": 1.58,
#             "armor penetration": 0.36,
#         },
#         "Beast Mastery": {
#             "strength": 0.15,
#             "agility": 2.5,
#             "intellect": 0.01,
#         
#             "hit": 3.57,
#             "attack power": 1.00,
#             "crit": 1.78,
#             "haste": 1.58,
#             "armor penetration": 0.36,
#         },
#         "Marksmanship": {
#             "strength": 0.15,
#             "agility": 2.5,
#             "intellect": 0.01,
#         
#             "hit": 3.57,
#             "attack power": 1.00,
#             "crit": 1.78,
#             "haste": 1.58,
#             "armor penetration": 0.36,
#         },
#     },
# },
# hunter = {
#     "strength": 0.15,
#     "agility": 2.5,
#     "intellect": 0.01,
# 
#     "hit": 3.57,
#     "attack power": 1.00,
#     "crit": 1.78,
#     "haste": 1.58,
#     "armor penetration": 0.36,
# }

# mage = {
#     "intellect": 1.57,
#     "spirit": 0.99,
#     "spell damage": 1.00,
#     "arcane damage": 0.78,
#     "spell hit": 1.38,
#     "spell crit": 0.83,
#     "spell haste": 0.77,
#     "mp5": 0.59,
# }

# paladin = {
#     "strength": 2.77,
#     "agility": 2.05,
#     "intellect": 0.38,
# 
#     "hit": 0.53,
#     "expertise": 5.65,
#     "attack power": 1.00,
#     "crit": 2.15,
#     "haste": 2.55,
#     "armor penetration": 0.27,
# }

# priest = {
#     "intellect": 0.09,
#     "spirit": 0.11,
#     "spell damage": 1.00,
#     "shadow damage": 0.96,
#     "spell hit": 0.00,
#     "spell crit": 0.18,
#     "spell haste": 0.90,
# }

# rogue = {
#     "strength": 1.10,
#     "agility": 2.23,
#     "hit": 2.55,
#     "expertise": 3.43,
#     "attack power": 1.00,
#     "crit": 1.82,
#     "haste": 2.32,
#     "armor penetration": 0.34,
# }

# shaman = {
#     "strength": 2.20,
#     "agility": 1.69,
#     "intellect": 0.03,
# 
#     "hit": 1.00,
#     "expertise": 2.81,
#     "attack power": 1.00,
#     "crit": 1.68,
#     "haste": 1.50,
#     "armor penetration": 0.27,
#     "intellect": 2.27,
#     "spirit": 3.61,
#     "spell damage": 1.00,
#     "arcane damage": 0.17,
#     "nature damage": 1.00,
#     "spell hit": 1.80,
#     "spell crit": 1.00,
#     "spell haste": 1.33,
#     "mp5": 0.34,
# }

# priest = {
#     "intellect": 0.39,
#     "spell damage": 1.00,
#     "shadow damage": 0.93,
#     "spell hit": 2.14,
#     "spell crit": 0.69,
#     "spell haste": 0.96,
#     "mp5": 0.23,
# }

# warrior = {
#     "strength": 1.79,
#     "agility": 1.01,
#     "hit": 0.97,
#     "expertise": 2.02,
#     "attack power": 1.00,
#     "crit": 1.31,
#     "haste": 1.54,
#     "armor penetration": 0.29,
# }


classes = {
    "Druid": {
        "Balance": {
            "intellect": 0.54,
            "spirit": 0.1,
            "spell damage": 1.0,
            "arcane damage": 1.0,
            "spell hit": 3.28,
            "spell crit": 0.84,
            "spell haste": 1.29,
        },
        "Feral DPS": {
            "strength": 2.266,
            "agility": 3.5,
            "attack power": 1.00,
            "crit": 2.37,
            "hit": 3.2,
            "haste": 1.36,
            "expertise": 3.2,
            "armor penetration": 0.47,
            },
        "Feral Tank": {
            "armor": 0.59,
            "stamina": 3.05,
            "strength": 2.266,
            "agility": 4.6,
            "attack power": 1.00,
            "crit": 1.0,
            "hit": 3.5,
            "haste": 1.6,
            "expertise": 7.3,
            "armor penetration": 0.34,
            "defense": 2.2,
            "dodge": 1.7,
            "resilience": 1.7,
            },
        "Restoration": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell damage": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        }
    },
    "Hunter": {
        "Beast Mastery": {
            "agility": 2.5,
            "intellect": 0.01,
            "strength": 0.15,
            "attack power": 1.00,
            "crit": 2.3,
            "hit": 0.3,
            "haste": 1.97,
            "armor penetration": 0.4,
        },
        #Find weights for marks and surv
        "Marksmanship": {
            "agility": 2.5,
            "intellect": 0.01,
            "strength": 0.15,
            "attack power": 1.00,
            "crit": 2.3,
            "hit": 0.3,
            "haste": 1.97,
            "armor penetration": 0.4,
        },
        "Survival": {
            "agility": 2.5,
            "intellect": 0.01,
            "strength": 0.15,
            "attack power": 1.00,
            "crit": 2.3,
            "hit": 0.3,
            "haste": 1.97,
            "armor penetration": 0.4,
        },
    },
    "Mage": {
        "Arcane": {
            "intellect": 1.29,
            "spirit": 0.89,
            "spell power": 1.0,
            "arcane spell power": 0.78,
            "frost spell power": 0.78,
            "spell crit": 0.77,
            "spell hit": 1.26,
            "spell haste": 0.84,
            "mp5": 0.61,
        },
        # Find weight for Fire and Frost
        "Fire": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell damage": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "fire damage": 0.0,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
        "Frost": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell damage": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
    },
    "Paladin": {
        "Holy": {
            "intellect": 2.27,
            "spirit": 3.61,
            "healing power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
        "Protection": {
            "armor": 0.05,
            "stamina": 1,
            "strength": 0.33,
            "agility": 0.6,
            "attack power": 0.06,
            "crit": 0.28,
            "hit": 0.67,
            "haste": 0.21,
            "armor penetration": 0.19,
            "expertise" : 0.67,
            "block": 0.35,
            "block value": 0.59,
            "dodge": 0.7,
            "parry": 0.58,
            "defense": 0.8,
        },
        "Retribution": {
            "strength": 2.42,
            "agility": 1.88,
            "intellect": 0.01,
            "attack power": 1.00,
            "crit": 1.98,
            "hit": 3.57,
            "expertise" : 4.70,
            "haste": 3.27,
            "armor penetration": 0.24,
            "spell power": 0.35,
        },
    },
    "Priest": {
        "Discipline": {
            "intellect": 2.27,
            "spirit": 3.61,
            "healing power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
        "Holy": {
            "intellect": 2.27,
            "spirit": 3.61,
            "healing power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
        "Shadow": {
            "intellect": 0.05,
            "spirit": 0.11,
            "spell power": 1,
            "shadow spell power": 1,
            "spell hit": 0,
            "spell crit": 0.163,
            "spell haste": 1.1,
            "mp5": 0.06,
        },
    },
    "Rogue": {
        "Assassination": {
            "agility": 2.214,
            "strength": 1.1,
            "attack power": 1.00,
            "crit": 1.763,
            "hit": 2.852,
            "haste": 2.311,
            "armor penetration": 0.44,
            "expertise" : 3.107,
        },
        "Combat": {
            "agility": 2.214,
            "strength": 1.1,
            "attack power": 1.00,
            "crit": 1.763,
            "hit": 2.852,
            "haste": 2.311,
            "armor penetration": 0.44,
            "expertise" : 3.107,
        },
        "Subtlety": {
            "agility": 2.214,
            "strength": 1.1,
            "attack power": 1.00,
            "crit": 1.763,
            "hit": 2.852,
            "haste": 2.311,
            "armor penetration": 0.44,
            "expertise" : 3.107,
        },
    },
    "Shaman": {
        "Elemental": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
        "Enhancement": {
            "strength": 0.15,
            "agility": 2.5,
            "intellect": 0.01,
            "hit": 3.57,
            "attack power": 1.00,
            "crit": 1.78,
            "haste": 1.58,
            "armor penetration": 0.36,
        },
        "Restoration": {
            "intellect": 2.27,
            "spirit": 3.61,
            "healing power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
    },
    "Warlock": {
        "Affliction": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
            },
        "Demonology": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
            },
        "Destruction": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell power": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
            },
        },
    "Warrior": {
        "Arms": {
            "strength": 0.15,
            "agility": 2.5,
            "hit": 3.57,
            "attack power": 1.00,
            "crit": 1.78,
            "haste": 1.58,
            "armor penetration": 0.36,
            "expertise" : 8.48,
        },
        "Fury": {
            "strength": 0.15,
            "agility": 2.5,
            "hit": 3.57,
            "attack power": 1.00,
            "crit": 1.78,
            "haste": 1.58,
            "armor penetration": 0.36,
            "expertise" : 8.48,
        },
        "Protection": {
            "strength": 2.55,
            "agility": 1.33,
            "hit": 0.00,
            "attack power": 1.00,
            "crit": 2.43,
            "haste": 1.58,
            "armor penetration": 0.34,
            "expertise" : 8.48,
        },
    },
}

