classes = {
    "Druid": {
        "Balance": {
            "intellect": 0.54,
            "spirit": 0.1,
            "spell damage": 1.0,
            "arcane damage": 1.0,
            "spell hit": 3.28,
            "spell crit": 0.84,
            "spell haste": 1.29,
        },
        "Feral Dps": {
            "strength": 2.266,
            "agility": 3.5,
            "attack power": 1.00,
            "crit": 2.37,
            "hit": 3.2,
            "haste": 1.36,
            "expertise": 3.2,
            "armor penetration": 0.47,
            },
        "Feral Tank": {
            "armor": 0.59,
            "stamina": 3.05,
            "strength": 2.266,
            "agility": 4.6,
            "attack power": 1.00,
            "crit": 1.0,
            "hit": 3.5,
            "haste": 1.6,
            "expertise": 7.3,
            "armor penetration": 0.34,
            "defense": 2.2,
            "dodge": 1.7,
            "resilience": 1.7,
            },
        "Restoration": {
            "intellect": 0.5,
            "stamina": 0.2,
            "healing power": 1.0,
            "spell crit": 0.6,
            "spell haste": 1.5,
            "mp5": 2.0,
        }
    },
    "Hunter": {
        "Beast Mastery": {
            "agility": 2.5,
            "intellect": 0.01,
            "strength": 0.15,
            "attack power": 1.00,
            "crit": 2.3,
            "hit": 0.3,
            "haste": 1.97,
            "armor penetration": 0.4,
        },
        "Marksmanship": {
            "agility": 2.5,
            "intellect": 0.01,
            "strength": 0.15,
            "attack power": 1.00,
            "crit": 2.3,
            "hit": 0.3,
            "haste": 1.97,
            "armor penetration": 0.4,
        },
        "Survival": {
            "agility": 2.5,
            "intellect": 0.01,
            "strength": 0.15,
            "attack power": 1.00,
            "crit": 2.3,
            "hit": 0.3,
            "haste": 1.97,
            "armor penetration": 0.4,
        },
    },
    "Mage": {
        "Arcane": {
            "intellect": 1.29,
            "spirit": 0.89,
            "spell power": 1.0,
            "arcane spell power": 0.78,
            "frost spell power": 0.78,
            "spell crit": 0.77,
            "spell hit": 1.26,
            "spell haste": 0.84,
            "mp5": 0.61,
        },
        "Fire": {
            "intellect": 0.2,
            "spirit": 0.11,
            "spell damage": 0.38,
            "arcane damage": 0.17,
            "fire damage": 1.0,
            "spell hit": 1.6,
            "spell crit": 0.7,
            "spell haste": 1.2,
        },
        "Frost": {
            "intellect": 2.27,
            "spirit": 3.61,
            "spell damage": 0.38,
            "arcane damage": 0.17,
            "nature damage": 1.00,
            "spell hit": 3.28,
            "spell crit": 1.00,
            "spell haste": 2.54,
            "mp5": 1.53,
        },
    },
    "Paladin": {
        "Holy": {
            "intellect": 0.5,
            "stamina": 0.2,
            "healing power": 1.0,
            "spell crit": 0.6,
            "spell haste": 1.5,
            "mp5": 2.0,
        },
        "Protection": {
            "armor": 0.05,
            "stamina": 1,
            "strength": 0.33,
            "agility": 0.6,
            "attack power": 0.06,
            "crit": 0.28,
            "hit": 0.67,
            "haste": 0.21,
            "armor penetration": 0.19,
            "expertise" : 0.67,
            "block": 0.35,
            "block value": 0.59,
            "dodge": 0.7,
            "parry": 0.58,
            "defense": 0.8,
        },
        "Retribution": {
            "strength": 2.42,
            "agility": 1.88,
            "intellect": 0.01,
            "attack power": 1.00,
            "crit": 1.98,
            "hit": 3.57,
            "expertise" : 4.70,
            "haste": 3.27,
            "armor penetration": 0.24,
            "spell power": 0.35,
        },
    },
    "Priest": {
        "Discipline": {
            "intellect": 0.5,
            "stamina": 0.2,
            "healing power": 1.0,
            "spell crit": 0.6,
            "spell haste": 1.5,
            "mp5": 2.0,
        },
        "Holy": {
           "intellect": 0.5,
            "stamina": 0.2,
            "healing power": 1.0,
            "spell crit": 0.6,
            "spell haste": 1.5,
            "mp5": 2.0,
        },
        "Shadow": {
            "intellect": 0.05,
            "spirit": 0.11,
            "spell power": 1,
            "shadow spell power": 1,
            "spell hit": 0,
            "spell crit": 0.163,
            "spell haste": 1.1,
            "mp5": 0.06,
        },
    },
    "Rogue": {
        "Assassination": {
            "agility": 2.214,
            "strength": 1.1,
            "attack power": 1.00,
            "crit": 1.763,
            "hit": 2.852,
            "haste": 2.311,
            "armor penetration": 0.44,
            "expertise" : 3.107,
        },
        "Combat": {
            "agility": 2.214,
            "strength": 1.1,
            "attack power": 1.00,
            "crit": 1.763,
            "hit": 2.852,
            "haste": 2.311,
            "armor penetration": 0.44,
            "expertise" : 3.107,
        },
        "Subtlety": {
            "agility": 2.214,
            "strength": 1.1,
            "attack power": 1.00,
            "crit": 1.763,
            "hit": 2.852,
            "haste": 2.311,
            "armor penetration": 0.44,
            "expertise" : 3.107,
        },
    },
    "Shaman": {
        "Elemental": {
            "intellect": 0.33,
            "spell power": 1.0,
            "nature spell power": 1.00,
            "spell hit": 2.41,
            "spell crit": 0.78,
            "spell haste": 1.25,
            "mp5": 0.08,
        },
        "Enhancement": {
            "strength": 2.2,
            "agility": 1.317,
            "intellect": 0.078,
            "attack power": 1.00,
            "hit": 1.665,
            "crit": 1.357,
            "haste": 1.944,
            "expertise": 2.871,
            "armor penetration": 0.283,
            "spell power": 0.433,
        },
        "Restoration": {
            "intellect": 0.5,
            "stamina": 0.2,
            "healing power": 1.0,
            "spell crit": 0.6,
            "spell haste": 1.5,
            "mp5": 2.0,
        },
    },
    "Warlock": {
        "Affliction": {
            "intellect": 0.4,
            "stamina": 0.058,
            "spirit": 0.1,
            "spell power": 1.0,
            "shadow spell power": 1.0,
            "fire spell power": 1.00,
            "spell hit": 3.28,
            "spell crit": 0.8,
            "spell haste": 1.2,
            "mp5": 0.0,
            },
        "Demonology": {
            "intellect":  0.22,
            "stamina": 0.058,
            "spirit": 0.1,
            "spell power": 1.0,
            "spell hit": 1.59,
            "spell crit": 0.59,
            "spell haste": 1.36,
            },
        "Destruction": {
            "intellect": 0.25,
            "stamina": 0.058,
            "spirit": 0.1,
            "spell power": 1.0,
            "shadow spell power": 1.0,
            "fire spell power": 1.00,
            "spell hit": 3.28,
            "spell crit": 0.8,
            "spell haste": 1.35,
            },
        },
    "Warrior": {
        "Arms": {
            "strength": 2.17,
            "agility": 1.4,
            "attack power": 1.00,
            "crit": 1.78,
            "hit": 0.41,
            "haste": 2.07,
            "armor penetration": 0.5,
            "expertise" : 3.29,
        },
        "Fury": {
            "strength": 2.17,
            "agility": 1.4,
            "attack power": 1.00,
            "crit": 1.78,
            "hit": 0.41,
            "haste": 2.07,
            "armor penetration": 0.5,
            "expertise" : 3.29,
        },
        "Protection": {
            "armor": 0.05,
            "stamina": 1,
            "strength": 0.33,
            "agility": 0.6,
            "attack power": 0.06,
            "crit": 0.28,
            "hit": 0.67,
            "haste": 0.21,
            "expertise": 0.67,
            "armor penetration": 0.19,
            "block": 0.35,
            "block value": 0.59,
            "dodge": 0.7,
            "parry": 0.58,
            "defense": 0.8,
        },
    },
}

